// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"github.com/horonlee/krathub/api/gen/go/conf/v1"
	"github.com/horonlee/krathub/app/sayhello/service/internal/server"
	"github.com/horonlee/krathub/app/sayhello/service/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

func wireApp(confServer *conf.Server, logger log.Logger) (*kratos.App, func(), error) {
	sayHelloService := service.NewSayHelloService()
	grpcServer := server.NewGRPCServer(confServer, logger, sayHelloService)
	app := newApp(logger, grpcServer)
	return app, func() {
	}, nil
}
