server:
  http:
    addr: "0.0.0.0:8000"
    timeout: "1s"
    tls:
      enable: false
      cert_path: "../../manifest/certs/server.cert"
      key_path: "../../manifest/certs/server.key"
    cors:
      enable: true
      allowed_origins: ["*"]
      allowed_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
      allowed_headers: ["Origin", "Content-Type", "Accept", "Authorization"]
      exposed_headers: []
      allow_credentials: false
      max_age: "86400s"
  grpc:
    addr: "0.0.0.0:8001"
    timeout: "1s"
    tls:
      enable: false
      cert_path: "../../manifest/certs/server.cert"
      key_path: "../../manifest/certs/server.key"

data:
  database:
    driver: "mysql"
    source: "root:password@tcp(127.0.0.1:3306)/krathub?parseTime=True&loc=Local"
  redis:
    addr: "127.0.0.1:6379"
    user_name: ""
    password: ""
    db: 0
  client:
    grpc: []

app:
  env: "dev"
  metadata: {}
  jwt:
    secret_key: "krathub_default_secret_change_in_production"
    expire: "24"
    issuer: "krathub"
  log:
    level: "0"
    max_size: "20"
    max_age: "30"
    max_backups: "10"

metrics:
  enable: true
  meter_name: "krathub"
