// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"github.com/horonlee/krathub/api/gen/go/conf/v1"
	"github.com/horonlee/krathub/app/krathub/service/internal/biz"
	"github.com/horonlee/krathub/app/krathub/service/internal/data"
	"github.com/horonlee/krathub/app/krathub/service/internal/server"
	"github.com/horonlee/krathub/app/krathub/service/internal/server/middleware"
	"github.com/horonlee/krathub/app/krathub/service/internal/service"
	"github.com/horonlee/krathub/pkg/transport/client"
)

import (
	_ "embed"
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, discovery *conf.Discovery, registry *conf.Registry, confData *conf.Data, app *conf.App, trace *conf.Trace, metrics *conf.Metrics, logger log.Logger) (*kratos.App, func(), error) {
	registrar := server.NewRegistrar(registry)
	serverMetrics, err := server.NewMetrics(metrics, logger)
	if err != nil {
		return nil, nil, err
	}
	grpcMiddleware := server.NewGRPCMiddleware(trace, serverMetrics, logger)
	grpcServer := server.NewGRPCServer(confServer, grpcMiddleware, logger)
	authJWT := middleware.NewAuthMiddleware(app)
	httpMiddleware := server.NewHTTPMiddleware(trace, serverMetrics, logger, authJWT)
	db, err := data.NewDB(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	registryDiscovery := data.NewDiscovery(discovery)
	clientClient, err := client.NewClient(confData, trace, registryDiscovery, logger)
	if err != nil {
		return nil, nil, err
	}
	redisClient, cleanup, err := data.NewRedis(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	dataData, cleanup2, err := data.NewData(db, confData, logger, clientClient, redisClient)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	authRepo := data.NewAuthRepo(dataData, logger)
	authUsecase := biz.NewAuthUsecase(authRepo, logger, app)
	authService := service.NewAuthService(authUsecase)
	userRepo := data.NewUserRepo(dataData, logger)
	userUsecase := biz.NewUserUsecase(userRepo, logger, app, authRepo)
	userService := service.NewUserService(userUsecase)
	testRepo := data.NewTestRepo(dataData, logger)
	testUsecase := biz.NewTestUsecase(testRepo, logger)
	testService := service.NewTestService(testUsecase)
	httpServer := server.NewHTTPServer(confServer, httpMiddleware, serverMetrics, logger, authService, userService, testService)
	kratosApp := newApp(logger, registrar, grpcServer, httpServer)
	return kratosApp, func() {
		cleanup2()
		cleanup()
	}, nil
}
